### ISSUE TITLE
Duplicated VOs on list 

### ISSUE THREAD

**Issue by andrea-manzi** [tdviet/fedcloudclient#49]
Hi Viet,

i see multiple VOs listed when running _fedcloud token list-vos_ :

```
fedcloud token list-vos
d4science.org
dteam
ggus-supporters.egi.eu
registry
training.egi.eu
vo.access.egi.eu
vo.binare-oy.eu
vo.binare-oy.eu
vo.emphasisproject.eu
vo.envri-fair.eu
vo.envri-fair.eu
vo.nextgeoss.eu
vo.notebooks.egi.eu
vo.notebooks.egi.eu
vo.openrdm.eu
vo.openrdm.eu
vo.panosc.eu
vo.seadatanet.org
vo.seadatanet.org
```
i guess because i have multiple entitlements there

Andrea

**Comment by tdviet** [comment]
Yes, confirming the bug. If the users have more roles of the same VO in eduperson_entitlement, e.g. 

urn:mace:egi.eu:group:VO_NAME:role=vm_operator#aai.egi.eu
urn:mace:egi.eu:group:VO_NAME:admins:role=member#aai.egi.eu

the VO_NAME will be duplicated.

**Comment by tdviet** [comment]
@enolfc Is it better if we change the regex in https://github.com/tdviet/fedcloudclient/blob/master/fedcloudclient/checkin.py#L174 from "role=member#aai.egi.eu" 
 to "role=vm_operator#aai.egi.eu"?

**Comment by enolfc** [comment]
It's actually a bit tricky, in the sense that not every VO with access to cloud will use the same kind of membership. Some require vm_operator, other may have something like admin (we are doing that for vo.notebooks.egi.eu). 

I would either filter out duplicates (e.g. we use a set instead of a list in https://github.com/tdviet/fedcloudclient/blob/master/fedcloudclient/checkin.py#L173, easy to do and I would say quite accurate) or we use exact matching for every single VO, which at the moment we don't have such an authoritative list.

**Comment by tdviet** [comment]
Fixed.
https://github.com/tdviet/fedcloudclient/commit/650f1038f2c205ddae5eec5f4abb29dcb97c2968

**Comment by andrea-manzi** [comment]
thanks!
